# Generated by Django 6.0.6 on 2026-06-22 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('factor_marca', models.DecimalField(decimal_places=3, default=1.0, help_text='Multiplicador de prima base por marca (ej: 1.2 = 20% más caro)', max_digits=5)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TarifaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cobertura', models.CharField(choices=[('rco', 'Resp. Civil Obligatoria'), ('terceros', 'Terceros Completo'), ('terceros_plus', 'Terceros Plus'), ('todo_riesgo', 'Todo Riesgo')], max_length=20, unique=True)),
                ('tasa_base', models.DecimalField(decimal_places=4, help_text='% anual sobre valor venal (ej: 0.0350 = 3.50%)', max_digits=6)),
                ('descripcion', models.TextField(blank=True)),
                ('incluye', models.JSONField(default=list, help_text='Lista de coberturas incluidas')),
                ('franquicia_pct', models.DecimalField(decimal_places=2, default=0, help_text='% de franquicia sobre valor venal', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='FactorRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('zona', 'Zona geográfica'), ('uso', 'Uso del vehículo'), ('edad_conductor', 'Edad del conductor'), ('antiguedad', 'Antigüedad del vehículo'), ('siniestralidad', 'Historial de siniestros')], max_length=30)),
                ('codigo', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('factor', models.DecimalField(decimal_places=3, help_text='Multiplicador: 1.0 = sin cambio, 1.2 = +20%, 0.9 = -10%', max_digits=5)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['tipo', 'orden'],
                'unique_together': {('tipo', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('anio_desde', models.PositiveIntegerField()),
                ('anio_hasta', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_venal_base', models.DecimalField(decimal_places=2, help_text='Valor venal de referencia en ARS', max_digits=14)),
                ('segmento', models.CharField(choices=[('compacto', 'Compacto'), ('sedan', 'Sedán'), ('suv', 'SUV'), ('pickup', 'Pick-up'), ('utilitario', 'Utilitario'), ('deportivo', 'Deportivo')], default='compacto', max_length=50)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='cotizador.marca')),
            ],
            options={
                'ordering': ['marca__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('valor_venal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('nombre_conductor', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('edad_conductor', models.PositiveIntegerField()),
                ('dni', models.CharField(blank=True, max_length=20)),
                ('tiene_siniestros', models.BooleanField(default=False)),
                ('zona', models.CharField(max_length=50)),
                ('uso', models.CharField(max_length=50)),
                ('cobertura_elegida', models.CharField(max_length=20)),
                ('prima_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prima_anual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('factor_total', models.DecimalField(decimal_places=4, max_digits=6)),
                ('desglose', models.JSONField(default=dict)),
                ('estado', models.CharField(choices=[('generada', 'Generada'), ('enviada', 'Enviada por email'), ('contratada', 'Contratada'), ('vencida', 'Vencida')], default='generada', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cotizador.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cotizador.modelo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
